<?php
/**
 * @package     BabDev.UnitTest
 * @subpackage  HTTP
 *
 * @copyright   Copyright (C) 2012 Michael Babker. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */

/**
 * Test class for BDHttpFactory.
 * Generated by PHPUnit on 2012-05-05 at 06:25:26.
 *
 * @package     BabDev.UnitTest
 * @subpackage  HTTP
 * @since       1.0
 */
class BDHttpFactoryTest extends PHPUnit_Framework_TestCase
{
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers BDHttpFactory::getHttp
	 * @todo Implement testGetHttp().
	 */
	public function testGetHttp()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		  'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BDHttpFactory::getAvailableDriver
	 * @todo Implement testGetAvailableDriver().
	 */
	public function testGetAvailableDriver()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		  'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BDHttpFactory::getHttpTransports
	 * @todo Implement testGetHttpTransports().
	 */
	public function testGetHttpTransports()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		  'This test has not been implemented yet.'
		);
	}
}
